// c99 with 3 TC, POSIX 2001 with 2 TC
#define _POSIX_VERSION 200112L
#include <stdlib.h>
#include "./utils.h"
#include "./parsing.h"
#include "./intermediate.h"
static char* HelpText[] = {
    "Parser Debug:",
    "  watercress --test-parsing=(ptokens|stokens) ?--dbg=(escres) [file]",
    "    outputs the tokens generated by the parser",
    "    (ptokens) - outputs the parser tokens generated on first pass",
    "    (stokens) - outputs the semantic tokens generated by the parser",
    "    --dbg=",
    "      extra debugging for certain parts of the parser",
    "      (escres) - debug escape code resolution"
};
int main(int argc, char** argv) {
    if (argc > 1) {
        if (!strcmp(argv[1], "--help")) {
            int i = 0;
            while (HelpText[i]) {
                printf("%s\n", HelpText[i++]);
            }
            return EXIT_SUCCESS;
        }
    }
    if (argc > 2) {
        if (!strcmp(argv[1], "--test-parsing=ptokens")) {
            if (argc > 3) {
                for (int i = 2; i < argc; i ++) {
                    if (!strcmp(argv[i], "--dbg=escres")) {
                        DEBUG_ESCAPES = 1;
                    }
                }
            }
            parser_test_ptokens(argv[argc-1]);
        }
        if (!strcmp(argv[1], "--test-parsing=stokens")) {
            parser_test_stokens(argv[argc-1]);
        }
        if (!strcmp(argv[1], "--test-intermediate")) {
            LinkedList* tofollow = LINKED_OBJECTS;
            Token* output = parse_file(argv[argc-1], 0, tofollow);
            linkedlist_destroy(tofollow);

            Program *p = compile(output);
            print_program(p);
        }
    }
    
    /* HashMap *map = hashmap_create(&hashstr, &hashstr2, &streq); */
    
    /* hashmap_set(map, (void *)strmove("hello"), (void *)strmove("world")); */
    /* hashmap_set(map, (void *)strmove("hello2"), (void *)strmove("world2")); */
    /* hashmap_set(map, (void *)strmove("ahoy"), (void *)strmove("earth")); */
    /* hashmap_set(map, (void *)strmove("what's up"), (void *)strmove("planet")); */

    /* printf("%s\n", (char *)hashmap_get(map, (void *)strmove("hello"))); */
    /* printf("%s\n", (char *)hashmap_get(map, (void *)strmove("ahoy"))); */

    /* hashmap_set(map, (void *)strmove("jkjkdsf"), (void *)strmove("wieurqiure")); */
    /* hashmap_set(map, (void *)strmove("uiweuri"), (void *)strmove("cvxzm,cv")); */
    /* hashmap_set(map, (void *)strmove("nmncxvmn"), (void *)strmove("uiwerfds")); */
    /* hashmap_set(map, (void *)strmove("izuifx"), (void *)strmove("nrmenwqrm")); */
    /* hashmap_set(map, (void *)strmove("uixcuviz"), (void *)strmove("uijviox")); */
    /* hashmap_set(map, (void *)strmove("jkfdjsio"), (void *)strmove("jksjdkfweqer")); */

    /* printf("%s\n", (char *)hashmap_get(map, (void *)strmove("hello"))); */
    /* printf("%s\n", (char *)hashmap_get(map, (void *)strmove("ahoy"))); */

    /* hashmap_set(map, (void *)strmove("hello"), (void *)strmove("schartman")); */
    /* printf("%s\n", (char *)hashmap_get(map, (void *)strmove("hello"))); */

    /* hashmap_set(map, (void *)5, (void *)7); */
    /* hashmap_set(map, (void *)10, (void *)8); */
    /* hashmap_set(map, (void *)22, (void *)9); */

    /* printf("%ld\n", (long)(hashmap_get(map, (void *)5))); */
    /* printf("%ld\n", (long)(hashmap_get(map, (void *)10))); */
    /* printf("%ld\n", (long)(hashmap_get(map, (void *)22))); */
    
    /* hashmap_set(map, (void *)22, (void *)10); */
    /* printf("%ld\n", (long)(hashmap_get(map, (void *)22))); */
    
    /* hashmap_set(map, (void *)1, (void *)8); */
    /* hashmap_set(map, (void *)2, (void *)8); */
    /* hashmap_set(map, (void *)3, (void *)10); */
    /* hashmap_set(map, (void *)4, (void *)8); */
    /* hashmap_set(map, (void *)6, (void *)8); */
    /* hashmap_set(map, (void *)7, (void *)10); */

    /* printf("%ld\n", (long)(hashmap_get(map, (void *)5))); */
    /* printf("%ld\n", (long)(hashmap_get(map, (void *)10))); */
    /* printf("%ld\n", (long)(hashmap_get(map, (void *)22))); */
    
    /* hashmap_destroy(map); */

    return EXIT_SUCCESS;
}
