// c99
#include <stdlib.h>
#include "./utils.h"
#include "./parsing/parsing.h"
static char* HelpText[] = {
    "Parser Debug:",
    "  watercress --test-parsing=(ptokens|stokens) [file]",
    "    outputs the tokens generated by the parser",
    "    (ptokens) - outputs the parser tokens generated on first pass",
    "    (stokens) - outputs the semantic tokens generated by the parser"
};
int main(int argc, char** argv) {
    if (argc > 1) {
        if (!strcmp(argv[1], "--help")) {
            int i = 0;
            while (HelpText[i]) {
                printf("%s\n", HelpText[i++]);
            }
            return EXIT_SUCCESS;
        }
    }
    if (argc > 2) {
        if (!strcmp(argv[1], "--test-parsing=ptokens")) {
            parser_test_ptokens(argv[argc-1]);
        }
    }
    return EXIT_SUCCESS;
}
